### ISSUE TITLE
Redirect URIs with urn: schemes are prohibited

### ISSUE THREAD

**Issue by techspence** [vanvfields/Microsoft-365#15]
Hello there! Thank you for these great IR scripts. When I run `Start-AzureADIRCollection.ps1` I get the following error when trying to authenticate:

```
azureadir AADSTS500119: Redirect URIs with urn: schemes are prohibited. Use a different scheme, or https://login.microsoftonline.com/common/oauth2/nativeclient
```

I have installed and imported `AzureADIncidentResponse` and I have tried your other scripts and several others seem to run OK, such as `Start-UnifiedAuditLogIRCollection.ps1`. 

Any ideas how to correct this? Thank you!

**Comment by vanvfields** [comment]
I am trying to reproduce the error above and not having any luck... I wonder if there is a difference in geography or something? I am in USA.  Otherwise, I am on an up-to-date Win10 machine, I start by launching a PowerShell session as admin, setting execution policy and then navigating to the directory and running the script. Have not been able to get the result you mention yet...
